#!/bin/sh

rm U_* alpha_*
rm -rf post*
blockMesh
cp -r 0.org/* 0/
setFields
decomposePar -force 
mpirun -np 8 --oversubscribe hybridPorousInterFoam -parallel > log.solver &

###mpirun -np 8 --oversubscribe  hybridPorousInterFoam -parallel > log.solver &
